#ifndef ERRORHANDLER_H
#define ERRORHANDLER_H


#define STACK_OVERLOW -99
#define STACK_UNDERFLOW -9
#define MATH_FAIL -1
#define OTHER_OPERATIONFAIL -2
#define ZERODIFF -4
#define SWP_ERROR -3
#define SUCCESS 0

#endif /* ERRORHANDLER_H */